#Requires -RunAsAdministrator
<#
.SYNOPSIS
  XDR Lab — repeatable bootstrap for a Windows victim golden image.

.DESCRIPTION
  Run once from elevated PowerShell to configure RDP, OpenSSH, WinRM (HTTP), and
  related firewall rules for lab-standard access. Optional switches enable Chocolatey,
  browsers, SMB lab share, and Sysmon. Final OS tuning and realism remain manual.

.NOTES
  - This script does not install CALDERA Sandcat. Follow runtime/caldera-agent/bootstrap-windows.ps1
    generated by the appliance (`aella_cli lab scenario agent deploy`).
  - Static IP (e.g. 10.10.10.30) is documented in docs/windows-golden-image.md (GUI/NetShell or
    separate unattend/GPO). This script does not change network adapters by default.

.EXAMPLE
  .\windows-bootstrap.ps1

.EXAMPLE
  .\windows-bootstrap.ps1 -InstallChocolatey -InstallBrowsers -EnableLabSmb

.EXAMPLE
  .\windows-bootstrap.ps1 -SysmonInstallerPath 'D:\tools\Sysmon.exe' -SysmonConfigPath 'D:\tools\sysmon.xml'
#>
[CmdletBinding(SupportsShouldProcess = $false)]
param(
    [string] $Hostname,
    [string] $TimezoneId,
    [switch] $InstallChocolatey,
    [switch] $InstallBrowsers,
    [string] $SysmonInstallerPath,
    [string] $SysmonConfigPath,
    [switch] $EnableLabSmb,
    [string] $LabShareSubnetCidr = '10.10.10.0/24',
    [string] $CalderaBootstrapReadmePath,
    [switch] $SetRemoteSignedExecutionPolicy,
    [switch] $SkipRebootReminder,
    [switch] $WriteDefenderExclusionPlaceholder
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Step($Message) {
    Write-Host "[xdr-lab] $Message" -ForegroundColor Cyan
}

function Test-Administrator {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-Administrator)) {
    throw 'Run again from an elevated (Administrator) PowerShell session.'
}

$LabRoot = 'C:\XdrLab'
$Dirs = @(
    (Join-Path $LabRoot 'tests'),
    (Join-Path $LabRoot 'logs'),
    (Join-Path $LabRoot 'shares\public'),
    (Join-Path $LabRoot 'staging')
)

Write-Step 'Creating directories'
foreach ($d in $Dirs) {
    if (-not (Test-Path -LiteralPath $d)) {
        New-Item -ItemType Directory -Path $d -Force | Out-Null
    }
}

if ($Hostname) {
    Write-Step "Setting hostname: $Hostname"
    Rename-Computer -NewName $Hostname -Force
}

if ($TimezoneId) {
    Write-Step "Setting timezone: $TimezoneId"
    Set-TimeZone -Id $TimezoneId
}

if ($SetRemoteSignedExecutionPolicy) {
    Write-Step 'ExecutionPolicy RemoteSigned (LocalMachine)'
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force
}

# --- OpenSSH Server ---
Write-Step 'Checking / installing OpenSSH Server capability'
$sshCaps = @(Get-WindowsCapability -Online -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -like 'OpenSSH.Server*' })
$sshNotInstalled = $sshCaps | Where-Object { $_.State -ne 'Installed' } | Select-Object -First 1
if ($sshNotInstalled) {
    Add-WindowsCapability -Online -Name $sshNotInstalled.Name | Out-Null
}
elseif ($sshCaps.Count -eq 0) {
    Write-Warning 'OpenSSH.Server capability not found via Get-WindowsCapability. Check Windows edition/skus.'
}

$sshd = Get-Service sshd -ErrorAction SilentlyContinue
if ($sshd) {
    Set-Service -Name sshd -StartupType Automatic
    Start-Service sshd
}

# SSH firewall fallback when default rules are missing
$fwSsh = Get-NetFirewallRule -DisplayName 'OpenSSH SSH Server (sshd)' -ErrorAction SilentlyContinue
if (-not $fwSsh) {
    New-NetFirewallRule -Name 'xdr-lab-openssh-in' -DisplayName 'XDR Lab — OpenSSH (sshd)' `
        -Direction Inbound -Protocol TCP -LocalPort 22 -Action Allow | Out-Null
}

# --- RDP ---
Write-Step 'Enabling RDP'
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' `
    -Name 'fDenyTSConnections' -Value 0 -Type DWord
Enable-NetFirewallRule -DisplayGroup 'Remote Desktop' -ErrorAction SilentlyContinue
# English DisplayGroup match; non-English SKUs may need manual enablement of localized RDP rules.
Get-NetFirewallRule -ErrorAction SilentlyContinue |
    Where-Object {
        $_.Direction -eq 'Inbound' -and $_.Enabled -ne 'True' -and
        ($_.DisplayGroup -like '*Remote Desktop*')
    } |
    Enable-NetFirewallRule -ErrorAction SilentlyContinue
if (-not (Get-NetFirewallRule -DisplayName 'XDR Lab — RDP' -ErrorAction SilentlyContinue)) {
    New-NetFirewallRule -Name 'xdr-lab-rdp-in' -DisplayName 'XDR Lab — RDP' `
        -Direction Inbound -Protocol TCP -LocalPort 3389 -Action Allow | Out-Null
}

# --- PowerShell Remoting / WinRM ---
Write-Step 'PowerShell Remoting / WinRM'
try {
    Enable-PSRemoting -Force -SkipNetworkProfileCheck | Out-Null
}
catch {
    Write-Warning "Enable-PSRemoting: $_"
}

try {
    winrm quickconfig -quiet -force | Out-Null
}
catch {
    Write-Warning "winrm quickconfig: $_"
}

foreach ($display in @('Windows Remote Management (HTTP-In)', 'Windows Remote Management - Compatibility Mode (HTTP-In)')) {
    Enable-NetFirewallRule -DisplayName $display -ErrorAction SilentlyContinue
}

# WinRM HTTPS is not configured here (requires a certificate); lab use assumes HTTP on isolated L2.

# --- Chocolatey (optional) ---
if ($InstallChocolatey) {
    Write-Step 'Installing Chocolatey'
    if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        $env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path', 'User')
    }
}

if ($InstallBrowsers) {
    if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
        throw 'Browser install requires Chocolatey. Pass -InstallChocolatey as well.'
    }
    Write-Step 'Installing browsers (googlechrome, firefox)'
    choco install googlechrome firefox -y --no-progress
}

# --- Sysmon (optional) ---
if ($SysmonInstallerPath) {
    if (-not (Test-Path -LiteralPath $SysmonInstallerPath)) {
        throw "SysmonInstallerPath not found: $SysmonInstallerPath"
    }
    if (-not $SysmonConfigPath) {
        throw 'Sysmon install requires -SysmonConfigPath alongside -SysmonInstallerPath.'
    }
    if (-not (Test-Path -LiteralPath $SysmonConfigPath)) {
        throw "SysmonConfigPath not found: $SysmonConfigPath"
    }
    Write-Step "Installing Sysmon: $SysmonInstallerPath -i $SysmonConfigPath"
    & $SysmonInstallerPath -accepteula -i $SysmonConfigPath
}
else {
    Write-Step 'Sysmon: skipped (-SysmonInstallerPath / -SysmonConfigPath not set).'
}

# --- SMB share (optional, lab scope) ---
if ($EnableLabSmb) {
    Write-Step "Enabling SMB file share (subnet-scoped rule: $LabShareSubnetCidr)"
    $sharePath = Join-Path $LabRoot 'shares\public'
    if (-not (Get-SmbShare -Name 'XdrLabPublic' -ErrorAction SilentlyContinue)) {
        New-SmbShare -Name 'XdrLabPublic' -Path $sharePath -FullAccess 'Everyone' | Out-Null
    }
    Set-SmbShare -Name 'XdrLabPublic' -FolderEnumerationMode AccessBased -ErrorAction SilentlyContinue
    Enable-NetFirewallRule -DisplayGroup 'File and Printer Sharing' -ErrorAction SilentlyContinue
    if (-not (Get-NetFirewallRule -DisplayName 'XDR Lab — SMB 445 (lab subnet)' -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -Name 'xdr-lab-smb-labnet' -DisplayName 'XDR Lab — SMB 445 (lab subnet)' `
            -Direction Inbound -Protocol TCP -LocalPort 445 -RemoteAddress $LabShareSubnetCidr -Action Allow | Out-Null
    }
    Write-Warning 'SMB increases attack surface. Confirm this host is not exposed outside the lab subnet.'
}

# --- CALDERA helper readme ---
$readmeTarget = if ($CalderaBootstrapReadmePath) { $CalderaBootstrapReadmePath } else { Join-Path $LabRoot 'CALDERA-BOOTSTRAP.txt' }
$calderaLines = @(
    'XDR Lab — CALDERA Sandcat (manual steps)',
    '',
    '1) On the appliance host:',
    '     aella_cli lab scenario agent deploy',
    '2) Copy generated bootstrap-windows.ps1 to this VM',
    '   (typical path: <XDR_ROOT>/runtime/caldera-agent/bootstrap-windows.ps1)',
    '3) Run that script from elevated PowerShell on this VM',
    '4) In CALDERA UI -> Agents, confirm beacon / last_seen',
    '5) Ensure config/caldera-lab.json agent_vm_map.host_substrings matches this PC hostname patterns',
    '',
    'Details: docs/caldera-integration.md',
    ''
)
Write-Step "Writing CALDERA readme: $readmeTarget"
$calderaLines | Set-Content -LiteralPath $readmeTarget -Encoding UTF8

# --- Defender exclusion PLACEHOLDER ---
if ($WriteDefenderExclusionPlaceholder) {
    $defPath = Join-Path $LabRoot 'DEFENDER-EXCLUSIONS-PLACEHOLDER.txt'
    Write-Step "Defender exclusion placeholder: $defPath"
    @(
        '# Operator-edited only — apply exclusions separately after review (e.g. Add-MpPreference -ExclusionPath)',
        '# Example: Add-MpPreference -ExclusionPath "C:\XdrLab\staging"',
        ''
    ) | Set-Content -LiteralPath $defPath -Encoding UTF8
}

Write-Step 'Summary'
Write-Host "  Lab root: $LabRoot"
Write-Host '  Review firewall rules for RDP / OpenSSH / WinRM (HTTP) / PSRemoting.'

if (-not $SkipRebootReminder) {
    if ($Hostname) {
        Write-Warning 'A reboot may be required after hostname change.'
    }
    Write-Warning 'Reboot once to finalize some services (especially OpenSSH) before production lab use.'
}
